# Generated by Django 4.2.7 on 2026-02-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
