# Generated by Django 4.2.7 on 2026-02-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_students_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrolled_date',
            field=models.DateField(),
        ),
    ]
